### ISSUE TITLE
搜索功能可以麻烦适配一下官方QQ机器人吗

### ISSUE THREAD

**Issue by homeworkkun** [fafa-junhe/koishi-plugin-mcwiki-search#1]
官方机器人使用搜索功能后不管怎么输入数字都提示是错误的
![image](https://github.com/user-attachments/assets/56ca7a26-9dcd-4c9d-9729-490df9888710)
![image](https://github.com/user-attachments/assets/5b50ef4c-e9b9-4501-a8c2-9a552493b608)
![image](https://github.com/user-attachments/assets/c6996382-756e-4ab7-b514-7765996ce7f9)

**Comment by homeworkkun** [comment]
还有就是，.look指令对页面名字带空格的页面适配有问题，比如页面【佣兵 初始时装】页面，只能获取到【佣兵】页面
必须手动加下划线变成【佣兵_初始时装】
不过主要还是需要搜索的时候麻烦比较大

**Comment by fafa-junhe** [comment]
试试0.0.12版本 fcd73be ，我这边没有官方机器人，测试不了。如果可以的话说一声。

**Comment by homeworkkun** [comment]
辛苦您了，0.0.12版本下空格已经可以正常识别了，但是官方机器人好像还是不行

**Comment by homeworkkun** [comment]
![image](https://github.com/user-attachments/assets/b812df73-16a3-4062-a29f-52f2da56a341)
![image](https://github.com/user-attachments/assets/2a745df4-de9c-4763-886c-95de31bf8839)

**Comment by fafa-junhe** [comment]
再试试呢 0.0.13版本

**Comment by homeworkkun** [comment]
> 再试试呢 0.0.13版本

试了下还是不行……
我就先不迁移到qq官方bot吧……好多插件都有在官方机器人上用不了的问题，辛苦您了
