### ISSUE TITLE
可否自定义搜索超时时长

### ISSUE THREAD

**Issue by homeworkkun** [fafa-junhe/koishi-plugin-mcwiki-search#2]
![b8d7c7b3-9e54-46ee-bb2e-58f6ef7cf631](https://github.com/user-attachments/assets/5a1912bd-f7c4-4cce-bd8d-4fb6b3a397e6)
现有时间间隔过短

**Comment by fafa-junhe** [comment]
0.0.14已添加此功能 53ad85bdb256973761453c6d4ceec051e0505b7f
